// Thin wrapper over the wasm-bindgen bindings in ./pkg (generated by
// `pnpm run build:wasm`, see core/README.md) -- knows nothing about the UI or
// the worker message protocol, mirrors the layering `docs/wasm.md` describes
// for the aidedx/dedx_web family of apps: a dependency-free boundary in front
// of the generated module that everything else imports instead of `./pkg`
// directly.
import init, {
  estimate as wasmEstimate,
  init_panic_hook,
  WasmSimulation,
} from "./pkg/pulsed_ion_chamber_wasm.js";

let ready: Promise<void> | undefined;

/** Fetch and instantiate the wasm module. Safe to call more than once. */
export function loadWasm(): Promise<void> {
  if (!ready) {
    ready = init().then(() => {
      init_panic_hook();
    });
  }
  return ready;
}

export interface SimParams {
  eMevU: number;
  voltageV: number;
  electrodeGapCm: number;
  doseRateGyS: number;
  pulseDurationS: number;
  sampledRadiusCm: number;
  gridSizeUm: number;
}

export interface Estimate {
  ok: boolean;
  error: string | undefined;
  noXy: number;
  noZ: number;
  totalTimeSteps: number;
  numberOfTracksPerPulse: number;
  estimatedMemoryBytes: number;
  dtNs: number;
  letKevUm: number;
  trackRadiusUm: number;
}

/** Instant, allocation-free -- call `loadWasm()` first, but never await it in a hot path. */
export function estimate(params: SimParams): Estimate {
  const e = wasmEstimate(
    params.eMevU,
    params.voltageV,
    params.electrodeGapCm,
    params.doseRateGyS,
    params.pulseDurationS,
    params.sampledRadiusCm,
    params.gridSizeUm,
  );
  return {
    ok: e.ok,
    error: e.error,
    noXy: e.no_xy,
    noZ: e.no_z,
    totalTimeSteps: e.total_time_steps,
    numberOfTracksPerPulse: e.number_of_tracks_per_pulse,
    estimatedMemoryBytes: e.estimated_memory_bytes,
    dtNs: e.dt_ns,
    letKevUm: e.let_kev_um,
    trackRadiusUm: e.track_radius_um,
  };
}

export { WasmSimulation };
